### ISSUE TITLE
403 error for `uploadFiles`

### ISSUE THREAD

**Issue by FullstackWEB-developer** [aqeelshamz/uploadthing#2]
in `uploadFiles`, `"$apiUrlv6/uploadFiles"` is working well but I got 403 error in this line.
how can I solve it?
it agent issue please help me

![image](https://github.com/user-attachments/assets/ecb07bdd-53cd-4fca-9e95-e1ad97b8e648)

**Comment by aqeelshamz** [comment]
Fixed. The error was due to missing "X-Amz-Security-Token" in the request field.
